# Generated by Django 5.2.4 on 2025-08-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_listing_image_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="locked_jetons",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
