# Generated by Django 5.2.4 on 2025-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_profile_locked_jetons"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="jeton_value",
            new_name="token_value",
        ),
        migrations.AddField(
            model_name="listing",
            name="brand",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("women", "Women"),
                    ("men", "Men"),
                    ("kids", "Kids"),
                    ("home", "Home"),
                    ("electronics", "Electronics"),
                    ("entertainment", "Entertainment"),
                    ("hobbies", "Hobbies & collectibles"),
                    ("sports", "Sports"),
                ],
                default="home",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new_with_tag", "New with tag"),
                    ("new_without_tag", "New without tag"),
                    ("very_good", "Very good"),
                    ("good", "Good"),
                    ("satisfactory", "Satisfactory"),
                ],
                default="very_good",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_listings", to="api.profile"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="size",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
