# Generated by Django 5.2.5 on 2025-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_proposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("text", "Text"), ("offer", "Offer")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="offer_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
