# Generated by Django 5.2.5 on 2025-08-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_message_message_type_message_offer_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="offer_amount",
        ),
    ]
