# Generated by Django 5.2.5 on 2025-08-20 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_message_offer_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="proposition",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message",
                to="api.proposition",
            ),
        ),
    ]
