# Generated by Django 5.2.5 on 2025-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
