# Generated by Django 5.2.5 on 2025-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="listing",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
