# Generated by Django 5.2.5 on 2025-09-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.brand",
            ),
        ),
    ]
