# Generated by Django 5.2.6 on 2025-09-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_profile_city_profile_country_profile_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_MESSAGE", "New Message"),
                    ("NEW_PROPOSITION", "New Proposition"),
                    ("PROPOSITION_ACCEPTED", "Proposition Accepted"),
                    ("PROPOSITION_REJECTED", "Proposition Rejected"),
                    ("NEW_REVIEW", "New Review"),
                    ("NEW_TRANSACTION", "New Transaction"),
                ],
                max_length=30,
            ),
        ),
    ]
